name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: npm test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      -  run: node build/index.js
