name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: SSH into server and run 'whoami'
        run: ssh staging 'whoami' # expect root back
        
        # run: npm ci && npm run build && pm2 restart server

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install project
  #     - run: npm ci
  
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: npm test

  # deploy:
  #   needs: [build, test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     -  run: node build/index.js
