name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: SSH into server
        run: doctl compute ssh server

      - name: Run 'whoami'
        run: whoami
        # run: npm ci && npm run build && pm2 restart server

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install project
  #     - run: npm ci
  
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: npm test

  # deploy:
  #   needs: [build, test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     -  run: node build/index.js
